import core from "./worker-clean.js";

const NEWS = [
  { date: "29 Aug 2026", country: "Worldwide", title: "Tax planning profiles refreshed", text: "Destination VAT/GST planning data has been refreshed across the global tax profile set.", tag: "UPDATED" },
  { date: "28 Aug 2026", country: "San Marino", title: "Import-tax profile added", text: "San Marino tax planning coverage has been added to the destination profile set.", tag: "UPDATED" },
  { date: "28 Aug 2026", country: "Global", title: "Shipping estimates now account for product weight where available", text: "When a reliable product weight can be established, the planning range is adjusted accordingly.", tag: "NEW" }
];

function withHtml(response) {
  const type = response.headers.get("content-type") || "";
  if (!type.includes("text/html")) return response;
  const items = NEWS.map((n) => `<article style="padding:14px 0;border-bottom:1px solid #DDD8CC"><div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start"><strong style="color:#173B8F;font-family:Georgia,serif;font-size:18px">${n.title}</strong><span style="font-size:10px;font-weight:800;letter-spacing:.08em;color:#F36A21">${n.tag}</span></div><div style="font-size:11px;color:#7A7F84;margin-top:3px">${n.country} · ${n.date}</div><div style="font-size:13px;color:#616A74;margin-top:5px">${n.text}</div></article>`).join("");
  const upcoming = `<div style="margin-top:24px;padding-top:18px;border-top:1px solid #DDD8CC"><div style="font-size:11px;letter-spacing:.12em;text-transform:uppercase;font-weight:850;color:#F36A21">Upcoming changes</div><p style="font-size:13px;color:#616A74;margin:8px 0 0">We’ll add verified upcoming product-tax and import-regime changes here as they are identified.</p></div>`;
  const news = `<section id="tax-news" class="wrap" style="padding:12px 28px 70px"><div style="background:#FFFDF8;border:1px solid #DDD8CC;border-radius:18px;padding:24px;box-shadow:0 18px 50px rgba(23,59,143,.07)"><div style="display:flex;justify-content:space-between;gap:20px;align-items:flex-start"><div><div style="font-size:12px;letter-spacing:.13em;text-transform:uppercase;font-weight:850;color:#F36A21">Tax &amp; Import News</div><h2 style="font-family:Georgia,serif;color:#173B8F;margin:8px 0 4px;font-size:34px">Live planning updates.</h2><p style="margin:0;color:#616A74;font-size:13px">A running record of changes that may affect product estimates.</p></div><div style="background:#F7F3EA;border:1px solid #DDD8CC;border-radius:12px;padding:11px 13px;white-space:nowrap"><div style="font-size:10px;text-transform:uppercase;letter-spacing:.1em;font-weight:850;color:#F36A21">LIVE</div><div style="font-size:12px;font-weight:750;color:#173B8F;margin-top:2px">No new updates today</div></div></div><div style="margin-top:18px">${items}</div>${upcoming}<div style="margin-top:20px;font-size:11px;color:#7A7F84">Sources are reviewed and incorporated into the planning engine as reliable destination information becomes available. This feed is informational, not legal or customs advice.</div></div></section>`;
  const script = `<script>(function(){if(window.__gisProd)return;window.__gisProd=true;function init(){var country=document.getElementById('country');var card=document.querySelector('.estimate-card');if(card&&!document.getElementById('gisQty')){var d=document.createElement('div');d.id='gisQty';d.style.marginTop='14px';d.innerHTML='<div class="field-label">Quantity</div><div style="display:flex;align-items:center;justify-content:space-between;border:1px solid #CFC9BC;border-radius:13px;background:white;padding:10px 12px"><span>Identical items</span><span style="display:flex;gap:10px;align-items:center"><button type="button" id="gisMinus" style="width:32px;height:32px;border:1px solid #D5D0C5;border-radius:9px;background:#F7F3EA">−</button><b id="gisQtyNum">1</b><button type="button" id="gisPlus" style="width:32px;height:32px;border:1px solid #D5D0C5;border-radius:9px;background:#F7F3EA">+</button></span></div>';country.parentElement.parentElement.insertBefore(d,country.parentElement)}var result=document.getElementById('result');if(result&&!document.getElementById('gisQuote')){var q=document.createElement('div');q.id='gisQuote';q.style.marginTop='18px';q.innerHTML='<div style="padding:16px;border-radius:14px;background:#F4F1E9;border:1px solid #E1DBCD"><strong style="font-family:Georgia,serif;font-size:20px;color:#173B8F">Want the exact figure?</strong><p style="font-size:13px;color:#616A74;margin:6px 0 12px">Your estimate is a planning range. Request an official quote and we\'ll verify the retailer, shipping and destination charges.</p><button type="button" id="gisQuoteBtn" style="border:0;border-radius:11px;background:#F36A21;color:white;font-weight:800;padding:12px 16px;cursor:pointer">GET AN OFFICIAL QUOTE →</button></div>';result.appendChild(q);q.querySelector('#gisQuoteBtn').onclick=function(){var u=document.getElementById('url')?.value||'';var c=document.getElementById('country')?.value||'';var qty=document.getElementById('gisQtyNum')?.textContent||'1';var params=new URLSearchParams({url:u,destination:c,quantity:qty});window.location.hash='quote';alert('Quote request prepared. We will connect this button to the official quote submission workflow before launch.')}}}function setQty(v){v=Math.max(1,Math.min(99,v));var n=document.getElementById('gisQtyNum');if(n)n.textContent=v}document.addEventListener('DOMContentLoaded',init);setTimeout(init,500);document.addEventListener('click',function(e){if(e.target&&e.target.id==='gisMinus')setQty((+document.getElementById('gisQtyNum').textContent||1)-1);if(e.target&&e.target.id==='gisPlus')setQty((+document.getElementById('gisQtyNum').textContent||1)+1)})})();</script>`;
  return new HTMLRewriter().on("body",{element(el){el.append(news+script,{html:true});}}).transform(response);
}

export default { async fetch(request, env) { const url = new URL(request.url); const response = await core.fetch(request, env); if (url.pathname === "/" || url.pathname === "/index.html") return withHtml(response); return response; } };