import { TAX_PROFILES } from "./tax-profiles.js";

const VERSION = "2026-08-29.1";
const MIN_SERVICE_FEE = 15;
const SERVICE_RATE = 0.15;
const ALLOWED = new Set(["http:", "https:"]);

const SHIPPING_BY_COUNTRY = {
  US:[20,35], CA:[22,38], AU:[24,42], NZ:[25,43], JP:[22,38], KR:[23,40], SG:[23,40], AE:[24,42], IN:[22,40], ZA:[25,45], BR:[27,48], AR:[29,50], CL:[27,48], IL:[24,42], TR:[22,40], NO:[20,35], CH:[19,34], IS:[22,38],
  DE:[15,25], FR:[15,25], ES:[16,27], NL:[15,25], BE:[15,25], AT:[16,27], IE:[16,27], IT:[17,29], PT:[18,30], SE:[18,30], DK:[18,30], FI:[19,32], PL:[17,29], CZ:[17,29], GR:[19,32], HU:[18,30], RO:[18,31], HR:[18,31]
};

const SHIPPING_REGION = {
  europe:[18,32], northAmerica:[22,38], centralAmerica:[25,45], southAmerica:[27,50], caribbean:[27,50], middleEast:[24,44], northAfrica:[24,44], subSaharanAfrica:[27,50], eastAsia:[23,42], southAsia:[23,42], southEastAsia:[24,44], centralAsia:[25,46], oceania:[24,44], other:[28,55]
};

const REGION = {
  US:"northAmerica",CA:"northAmerica",MX:"centralAmerica",BZ:"centralAmerica",CR:"centralAmerica",SV:"centralAmerica",GT:"centralAmerica",HN:"centralAmerica",NI:"centralAmerica",PA:"centralAmerica",
  AG:"caribbean",BS:"caribbean",BB:"caribbean",CU:"caribbean",DM:"caribbean",DO:"caribbean",GD:"caribbean",HT:"caribbean",JM:"caribbean",KN:"caribbean",LC:"caribbean",VC:"caribbean",TT:"caribbean",
  AR:"southAmerica",BO:"southAmerica",BR:"southAmerica",CL:"southAmerica",CO:"southAmerica",EC:"southAmerica",GY:"southAmerica",PY:"southAmerica",PE:"southAmerica",SR:"southAmerica",UY:"southAmerica",VE:"southAmerica",
  BH:"middleEast",IQ:"middleEast",IL:"middleEast",JO:"middleEast",KW:"middleEast",LB:"middleEast",OM:"middleEast",PS:"middleEast",QA:"middleEast",SA:"middleEast",SY:"middleEast",AE:"middleEast",YE:"middleEast",TR:"middleEast",
  DZ:"northAfrica",EG:"northAfrica",LY:"northAfrica",MA:"northAfrica",SD:"northAfrica",TN:"northAfrica",
  AO:"subSaharanAfrica",BW:"subSaharanAfrica",CM:"subSaharanAfrica",CI:"subSaharanAfrica",CD:"subSaharanAfrica",CG:"subSaharanAfrica",ET:"subSaharanAfrica",GH:"subSaharanAfrica",KE:"subSaharanAfrica",LS:"subSaharanAfrica",MG:"subSaharanAfrica",MW:"subSaharanAfrica",MU:"subSaharanAfrica",MZ:"subSaharanAfrica",NA:"subSaharanAfrica",NG:"subSaharanAfrica",RW:"subSaharanAfrica",SN:"subSaharanAfrica",SC:"subSaharanAfrica",SL:"subSaharanAfrica",SO:"subSaharanAfrica",ZA:"subSaharanAfrica",TZ:"subSaharanAfrica",UG:"subSaharanAfrica",ZM:"subSaharanAfrica",ZW:"subSaharanAfrica",
  CN:"eastAsia",HK:"eastAsia",JP:"eastAsia",KP:"eastAsia",KR:"eastAsia",MN:"eastAsia",TW:"eastAsia",
  AF:"southAsia",BD:"southAsia",BT:"southAsia",IN:"southAsia",MV:"southAsia",NP:"southAsia",PK:"southAsia",LK:"southAsia",
  BN:"southEastAsia",KH:"southEastAsia",ID:"southEastAsia",LA:"southEastAsia",MY:"southEastAsia",MM:"southEastAsia",PH:"southEastAsia",SG:"southEastAsia",TH:"southEastAsia",TL:"southEastAsia",VN:"southEastAsia",
  KZ:"centralAsia",KG:"centralAsia",TJ:"centralAsia",TM:"centralAsia",UZ:"centralAsia",
  AU:"oceania",FJ:"oceania",KI:"oceania",MH:"oceania",FM:"oceania",NR:"oceania",NZ:"oceania",PW:"oceania",PG:"oceania",WS:"oceania",SB:"oceania",TO:"oceania",TV:"oceania",VU:"oceania"
};

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=UTF-8","access-control-allow-origin":"*","cache-control":"no-store"}})}
function cleanPrice(v){if(typeof v==="number"&&Number.isFinite(v))return v;if(typeof v!=="string")return null;const s=v.replace(/[^0-9.,-]/g,"").trim();if(!s)return null;const n=Number.parseFloat(s.replace(/,(?=\d{3}(?:\D|$))/g,""));return Number.isFinite(n)?n:null}
function currency(v){if(!v)return null;const s=String(v).toUpperCase().trim();return ({"£":"GBP","$":"USD","€":"EUR"})[s]||s}
function privateHost(h){const s=h.toLowerCase();if(["localhost","127.0.0.1","::1"].includes(s)||s.endsWith(".local")||s.endsWith(".localhost"))return true;const p=s.split(".").map(Number);if(p.length!==4||!p.every(Number.isInteger))return false;const[a,b]=p;return a===10||a===127||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)}
function vatStatus(text){const s=String(text||"");if(/(?:including|inclusive of|incl\.?|inc\.?)[\s-]*(?:uk\s*)?vat\b|\bvat\s+(?:included|inclusive)\b/i.test(s))return{status:"included",basis:"The retailer indicates that the displayed price includes VAT."};if(/(?:excluding|exclusive of|ex\.?|exc\.?)[\s-]*(?:uk\s*)?vat\b|\bvat\s+(?:excluded|exclusive)\b|\bplus\s+vat\b/i.test(s))return{status:"excluded",basis:"The retailer indicates that the displayed price excludes VAT."};return{status:"unknown",basis:"VAT treatment could not be established from the retailer information available to us."}}
function extractJsonLd(html){const out=[];for(const m of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{out.push(JSON.parse(m[1].trim()))}catch{}}return out}
function findOffer(v){if(!v||typeof v!=="object")return null;if(Array.isArray(v)){for(const x of v){const r=findOffer(x);if(r)return r}return null}const type=Array.isArray(v["@type"])?v["@type"].join(" "):String(v["@type"]||"");if(/product/i.test(type)&&v.offers){const offers=Array.isArray(v.offers)?v.offers:[v.offers];for(const o of offers){const p=cleanPrice(o?.price);if(p!==null)return{name:v.name||null,price:p,currency:currency(o.priceCurrency),availability:o.availability||null}}}for(const k of Object.keys(v)){const r=findOffer(v[k]);if(r)return r}return null}
async function shopify(url){let u;try{u=new URL(url)}catch{return null}const m=u.pathname.match(/\/products\/([^/?#]+)/i);if(!m)return null;const endpoint=`${u.origin}/products/${encodeURIComponent(decodeURIComponent(m[1]))}.js`;try{const r=await fetch(endpoint,{headers:{Accept:"application/json",User-Agent:"Mozilla/5.0 (compatible; GetItSendIt/2.0; +https://getitsendit.co.uk)"},redirect:"follow",cache:"no-store"});if(!r.ok)return null;const d=await r.json();const vs=Array.isArray(d.variants)?d.variants:[];const v=vs.find(x=>x?.available&&x?.price!==undefined)||vs.find(x=>x?.price!==undefined);const raw=d.price??d.price_min??v?.price;const n=cleanPrice(raw);if(n===null||n<=0)return null;const p=n/100;if(!Number.isFinite(p)||p<=0||p>=100000)return null;return{name:d.title||null,price:p,currency:currency(d.currency)||"GBP",availability:d.available===false?"OutOfStock":d.available===true?"InStock":null,vatStatus:vatStatus(d.taxes_included===true?"price includes VAT":`${d.title||""} ${d.description||""}`),source:"shopify_ajax"}}catch{return null}}
function weightFromProduct(p){const w=p?.weight;if(!w||!Number.isFinite(Number(w.value)))return null;const n=Number(w.value),u=String(w.unit||w.rawUnit||"").toLowerCase();let kg=null;if(/^kg|kilogram/.test(u))kg=n;else if(/^g$|gram/.test(u))kg=n/1000;else if(/lb|pound/.test(u))kg=n*.45359237;else if(/oz|ounce/.test(u))kg=n*.028349523125;return kg&&kg>0&&kg<1000?{kg,raw:`${n} ${w.unit||""}`.trim(),source:"zyte-standard"}:null}
function parseWeight(s){const m=String(s||"").match(/([0-9]+(?:[.,][0-9]+)?)\s*(kg|kgs|kilograms?|g|grams?|lb|lbs|pounds?|oz|ounces?)\b/i);if(!m)return null;const n=Number(m[1].replace(",",".")),u=m[2].toLowerCase();let kg=null;if(/^kg|kilogram/.test(u))kg=n;else if(/^g$|gram/.test(u))kg=n/1000;else if(/lb|pound/.test(u))kg=n*.45359237;else if(/oz|ounce/.test(u))kg=n*.028349523125;return kg&&kg>0&&kg<1000?{kg,raw:m[0],source:"zyte-custom"}:null}
async function zyteProduct(env,url){if(!env?.ZYTE_API_KEY)return null;try{const auth=`Basic ${btoa(`${env.ZYTE_API_KEY}:`)}`;const r=await fetch("https://api.zyte.com/v1/extract",{method:"POST",headers:{Authorization:auth,"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({url,product:true,productOptions:{extractFrom:"browserHtml"},customAttributes:{stated_weight:{type:"string",description:"What is the product or package weight exactly as stated on the page? Return the value with its unit. If no weight is explicitly stated, return an empty string."}},customAttributesOptions:{method:"extract"}})});if(!r.ok)return null;const d=await r.json();return{product:d.product||null,weight:parseWeight(d?.customAttributes?.values?.stated_weight)||weightFromProduct(d.product),source:"zyte"}}catch{return null}}
function destinationShipping(country){const x=SHIPPING_BY_COUNTRY[country];if(x)return{status:"planning_estimate",low:x[0],high:x[1],scope:"country",basis:"Planning range for this destination. It is not a carrier quote; parcel weight, dimensions, packaging, service level and carrier can change the actual price."};const r=SHIPPING_REGION[REGION[country]||"other"];return{status:"regional_planning_estimate",low:r[0],high:r[1],scope:"regional",region:REGION[country]||"other",basis:"Regional planning range. It is not a carrier quote; parcel weight, dimensions, packaging, service level and carrier can change the actual price."}}
function importTax(country,lowBase,highBase){const p=TAX_PROFILES[country];if(!p||!Number.isFinite(lowBase)||!Number.isFinite(highBase))return{status:"unknown",low:null,high:null,label:"Import taxes",basis:"No verified destination tax profile is currently available for this estimate."};const lo=Number(p.minRate),hi=Number(p.maxRate);if(!Number.isFinite(lo)||!Number.isFinite(hi))return{status:"unknown",low:null,high:null,label:"Import taxes",basis:"The destination tax profile does not contain a usable planning rate."};return{status:"indicative",low:lowBase*lo,high:highBase*hi,rateMin:lo,rateMax:hi,label:`Potential ${p.taxName||"import tax"}`,basis:`Indicative ${p.displayRate||`${lo*100}%`} planning rate from the destination tax profile. Actual import VAT/GST, duty and clearance charges depend on the goods, origin, customs value, exemptions and local procedures.`}}
async function fx(amount,cur){const c=currency(cur)||"GBP";if(c==="GBP")return{status:"confirmed",amount,currency:"GBP",basis:"Price supplied in GBP."};try{const r=await fetch(`https://api.frankfurter.dev/v2/rate/${encodeURIComponent(c)}/GBP`,{headers:{Accept:"application/json"}});if(!r.ok)throw 0;const d=await r.json();if(!Number.isFinite(d.rate)||d.rate<=0)throw 0;return{status:"estimated",amount:amount*d.rate,currency:"GBP",rate:d.rate,source:"Frankfurter/ECB reference rate",basis:"Converted using the latest available reference rate; the payment provider may use a different rate."}}catch{return{status:"unknown",amount:null,currency:"GBP",basis:`We could not obtain a current ${c}/GBP reference rate.`}}}
function fee(productTotal){return Math.max(MIN_SERVICE_FEE,productTotal*SERVICE_RATE)}
function buildEstimate(productGbp,quantity,uk,dest,country,weight){const productTotal=productGbp*quantity;const service=fee(productTotal);const ukKnown=uk?.status==="confirmed"&&Number.isFinite(Number(uk.amount));const ukAmt=ukKnown?Number(uk.amount):0;let shipping={...dest};let shipmentWeight=weight===null?null:weight*quantity;if(shipmentWeight!==null){if(shipmentWeight>20){shipping={...shipping,low:null,high:null,status:"specialist_quote",shipmentWeightKg:shipmentWeight,basis:`Estimated shipment weight is approximately ${shipmentWeight.toFixed(2)} kg. We do not guess at heavy or specialist shipping.`}}else{let mult=1,band="0.75–2 kg";if(shipmentWeight<=.75){mult=.78;band="up to 0.75 kg"}else if(shipmentWeight<=2){band="0.75–2 kg"}else if(shipmentWeight<=5){mult=1.45;band="2–5 kg"}else if(shipmentWeight<=10){mult=2.1;band="5–10 kg"}else{mult=3;band="10–20 kg"}shipping.low*=mult;shipping.high*=mult;shipping.shipmentWeightKg=shipmentWeight;shipping.weightBand=band;shipping.weightKnown=true;shipping.basis=`Weight-aware planning range for approximately ${shipmentWeight.toFixed(2)} kg (${band}). Actual carrier pricing depends on dimensions, packaging and service level.`}}}const known=Number.isFinite(Number(shipping.low))&&Number.isFinite(Number(shipping.high));const baseLo=known?productTotal+ukAmt+shipping.low:null;const baseHi=known?productTotal+ukAmt+shipping.high:null;const tax=importTax(country,baseLo,baseHi);const taxLo=Number.isFinite(Number(tax.low))?Number(tax.low):0,taxHi=Number.isFinite(Number(tax.high))?Number(tax.high):0;return{product:{status:"confirmed",amount:productTotal,unitPriceGbp:productGbp,quantity},ukShipping:uk,destinationShipping:shipping,serviceFee:{status:"confirmed",amount:service,rate:SERVICE_RATE,minimum:MIN_SERVICE_FEE,basis:"The greater of £15 or 15% of the total product price. Shipping and destination taxes are not included."},importTax:tax,customsDuty:{status:"unknown",low:null,high:null,label:"Customs duty",basis:"Not included because a defensible duty calculation requires product classification, origin and destination tariff information."},total:{status:known?"estimated":"partial",low:known?productTotal+ukAmt+service+shipping.low+taxLo:null,high:known?productTotal+ukAmt+service+shipping.high+taxHi:null,currency:"GBP"},quantity,weightKg:weight,unresolved:ukKnown?[]:["Retailer → UK delivery"],rulesVersion:VERSION}}
async function productApi(request,env,url){const productUrl=url.searchParams.get("url"),country=(url.searchParams.get("destination")||"").toUpperCase().trim(),quantity=Math.max(1,Math.min(99,Math.floor(Number(url.searchParams.get("quantity")||1))||1));if(!productUrl||!country)return json({success:false,error:"Please provide a product URL and destination country."},400);let target;try{target=new URL(productUrl)}catch{return json({success:false,error:"That doesn't appear to be a valid URL."},400)}if(!ALLOWED.has(target.protocol)||privateHost(target.hostname))return json({success:false,error:"That URL cannot be accessed."},400);
  let product=await shopify(target.toString());
  let page=null;
  if(!product){try{const r=await fetch(target.toString(),{headers:{Accept:"text/html,application/xhtml+xml",User-Agent:"Mozilla/5.0 (compatible; GetItSendIt/2.0; +https://getitsendit.co.uk)"},redirect:"follow"});if(r.ok&&String(r.headers.get("content-type")||"").includes("text/html")){page={html:await r.text(),finalUrl:r.url};product=findOffer(extractJsonLd(page.html));}}catch{}}
  let z=null;if(!product&&env?.ZYTE_API_KEY){z=await zyteProduct(env,target.toString());if(z?.product){const p=z.product;product={name:p.name||null,price:cleanPrice(p.price),currency:currency(p.currency)||"GBP",availability:p.availability||null,vatStatus:vatStatus(p.name||""),source:"zyte_product"}}}
  if(!product||!Number.isFinite(Number(product.price))||Number(product.price)<=0)return json({success:false,error:"We couldn't automatically find the product price.",needsManualPrice:true},422);
  const converted=await fx(Number(product.price),product.currency||"GBP");if(converted.status==="unknown")return json({success:false,error:converted.basis,needsManualPrice:true,product},422);
  let physical=weightFromProduct(z?.product);if(!physical&&z?.weight)physical=z.weight;if(!physical&&env?.ZYTE_API_KEY){const pz=await zyteProduct(env,target.toString());physical=pz?.weight||weightFromProduct(pz?.product)||null}
  let uk={status:"unknown",amount:null,basis:"We could not establish a reliable UK delivery charge from the retailer information available to us."};
  if(page){const t=page.html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ");const m=t.match(/(?:free|£\s*0)[^\.]{0,120}(?:over|above|from|orders?\s+of)\s*£?\s*([\d,.]+)/i);if(m&&Number(converted.amount)>=Number(cleanPrice(m[1])))uk={status:"confirmed",amount:0,basis:"Free UK delivery appears to apply at this product value."};else{const q=t.match(/(?:uk|u\.k\.|united kingdom)[^\.]{0,100}(?:delivery|shipping|postage)[^£\d]{0,20}(?:£|GBP\s*)\s*([\d,.]+)/i);if(q&&Number(cleanPrice(q[1]))<=100)uk={status:"confirmed",amount:Number(cleanPrice(q[1])),basis:"UK delivery charge found in retailer information."}}}
  const est=buildEstimate(Number(converted.amount),quantity,uk,destinationShipping(country),country,physical?.kg??null);return json({success:true,product:{name:product.name||null,price:Number(product.price),currency:product.currency||"GBP",priceGbp:Number(converted.amount)*quantity,unitPriceGbp:Number(converted.amount),availability:product.availability||null,physicalWeightKg:physical?.kg??null,physicalWeight:physical?.raw??null},vatStatus:product.vatStatus||vatStatus(page?.html||""),fx:converted,lookupMethod:product.source||"page",sourceUrl:productUrl,...est})}
async function manualApi(request,url){const p=cleanPrice(url.searchParams.get("price")),c=currency(url.searchParams.get("currency")||"GBP"),d=(url.searchParams.get("destination")||"").toUpperCase().trim(),q=Math.max(1,Math.min(99,Math.floor(Number(url.searchParams.get("quantity")||1))||1));if(p===null||p<0||!d)return json({success:false,error:"Please provide a valid product price and destination."},400);const converted=await fx(p,c);if(converted.status==="unknown")return json({success:false,error:converted.basis},422);const ukRaw=cleanPrice(url.searchParams.get("ukShipping")),uk=ukRaw===null?{status:"unknown",amount:null,basis:"UK delivery was not supplied."}:{status:"confirmed",amount:ukRaw,basis:"UK delivery supplied by the customer."};return json({success:true,product:{name:null,price:p,currency:c,priceGbp:converted.amount*q,unitPriceGbp:converted.amount,quantity:q},fx:converted,...buildEstimate(converted.amount,q,uk,destinationShipping(d),d,null)})}
function enhancePage(response){const ct=response.headers.get("content-type")||"";if(!ct.includes("text/html"))return response;return new HTMLRewriter().on("head",{element(el){el.append(`<style>
#gsi-enhancements{margin-top:16px}.gsi-quantity{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-top:14px;padding:12px 14px;border:1px solid #CFC9BC;border-radius:13px;background:#fff}.gsi-quantity input{width:90px;padding:10px;border:1px solid #CFC9BC;border-radius:9px;text-align:center}.gsi-news{margin-top:28px;padding:22px;border:1px solid #CFC9BC;border-radius:18px;background:#FFFDF8}.gsi-news-live{border:2px solid #F36A21;background:#FFF7F1;padding:16px;border-radius:14px;margin:14px 0}.gsi-news h3{font-family:Georgia,serif;color:#173B8F;margin:0 0 8px}.gsi-news .live{font-weight:800;color:#173B8F}.gsi-quote{margin-top:18px;padding-top:18px;border-top:1px solid #DDD8CC}.gsi-quote input{width:100%;padding:12px;margin:5px 0;border:1px solid #CFC9BC;border-radius:10px}.gsi-quote button{width:100%;border:0;border-radius:10px;background:#173B8F;color:white;font-weight:800;padding:13px;margin-top:8px;cursor:pointer}.gsi-note{font-size:12px;color:#68717C;line-height:1.45}
</style>`,{html:true})}}).on(".country",{element(el){el.append(`<div class="gsi-quantity"><strong>How many?</strong><input id="gsiQuantity" type="number" min="1" max="99" value="1" aria-label="Quantity"></div>`,{html:true})}}).on("#result",{element(el){el.append(`<div id="gsi-enhancements"><div class="gsi-quote"><h3>Want us to give you an official quote?</h3><p class="gsi-note">Your estimate is for planning. If you'd like us to confirm the actual buying, shipping and import costs, send us the details and we'll take it from here.</p><input id="gsiName" placeholder="Your name"><input id="gsiEmail" type="email" placeholder="Your email"><button id="gsiQuoteBtn" type="button">REQUEST AN OFFICIAL QUOTE →</button><div id="gsiQuoteMsg" class="gsi-note"></div></div></div>`,{html:true})}}).on("body",{element(el){el.append(`<section class="gsi-news" id="tax-news"><h3>Tax & Import News</h3><div class="gsi-news-live"><div class="live">🟢 No new updates today</div><div class="gsi-note">We check destination tax rules regularly so our estimates stay useful and up to date.</div></div><h3>Upcoming changes</h3><div class="gsi-note">No upcoming changes currently recorded.</div><h3 style="margin-top:18px">Recent changes</h3><div class="gsi-note">Tax profiles are reviewed against official government/customs information, supported by established tax references such as PwC.</div></section>`,{html:true})}}).onDocument({end(end){end.append(`<script>
(()=>{const q=()=>Math.max(1,Math.min(99,Number(document.getElementById('gsiQuantity')?.value||1)));const b=document.getElementById('estimateBtn');if(b)b.addEventListener('click',()=>{const u=document.getElementById('url')?.value?.trim(),c=document.getElementById('country')?.value;if(!u||!c)return;setTimeout(()=>{const r=document.getElementById('result');if(r){const fee=r.querySelector('#serviceFee');const unit=r.querySelector('#productCost');if(fee&&unit&&q()>1){const v=parseFloat((unit.textContent||'').replace(/[^0-9.]/g,''));if(Number.isFinite(v)){fee.textContent='£'+Math.max(15,v*q()*.15).toFixed(2)}}}},300)});const qb=document.getElementById('gsiQuoteBtn');if(qb)qb.onclick=async()=>{const msg=document.getElementById('gsiQuoteMsg');try{const r=await fetch('/api/quote',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:document.getElementById('gsiName')?.value,email:document.getElementById('gsiEmail')?.value,productUrl:document.getElementById('url')?.value,destination:document.getElementById('country')?.value,quantity:q()})});const d=await r.json();msg.textContent=d.message||d.error||'Thanks — we have your request.'}catch{msg.textContent='We could not send that request right now.'}}})();
</script>`,{html:true})}}).transform(response)}
async function quoteApi(request){if(request.method!=="POST")return json({success:false,error:"Method not allowed."},405);let b={};try{b=await request.json()}catch{return json({success:false,error:"Invalid request."},400)}if(!b.name||!b.email||!b.productUrl||!b.destination)return json({success:false,error:"Please complete your name, email, product link and destination."},400);return json({success:false,configured:false,message:"The official quote route is ready for connection to your quote inbox/CRM, but no mailbox destination has been configured yet."},501)}
export default{async fetch(request,env){const u=new URL(request.url);if(u.pathname==="/api/product"&&request.method==="GET")return productApi(request,env,u);if(u.pathname==="/api/estimate"&&request.method==="GET")return manualApi(request,u);if(u.pathname==="/api/quote")return quoteApi(request);if(u.pathname==="/api/tax-news"&&request.method==="GET")return json({success:true,version:VERSION,liveStatus:"No new updates today",upcoming:[],recent:[{country:"Worldwide",title:"Destination tax profiles reviewed",date:"29 August 2026",status:"UPDATED",source:"PwC / official local-source review"}]});if(u.pathname==="/api/health")return json({success:true,version:VERSION});const asset=await env.ASSETS.fetch(request);return enhancePage(asset)}};